### ISSUE TITLE
[Suggestion]: Make heads we get using beheading enchantment work with tinkers recipes

### ISSUE THREAD

**Issue by ivxvm** [DarkPacks/SkyFactory-One#142] opened 2021-11-13 17:22 UTC
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

I have a Supremium Sword with Beheading IV and the heads I get from blazes are called "MHF_Blaze's Head" (itemid is minecraft:player_head). Unfortunately they don't work in melting recipe for Blazing Blood (recipe expects tconstruct:blaze_head).

**Comment by sam-kirby** [comment] 2021-11-13 18:22
This is a duplicate of #126

**Closed** 2021-11-13 18:23 UTC
Labels: enhancement
