### ISSUE TITLE
[Bug]: CC:Tweaked Turtle place next to any storage crashed game

### ISSUE THREAD

**Issue by Tuckdu** [DarkPacks/SkyFactory-One#157] opened 2021-12-27 22:26 UTC
### General Info

- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.4

### Java version

Java 8 update 311

### Modpack Launcher Used

CurseForge Launcher

### Memory Allocated

8GB

### Minecraft World Environment

Server

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Server Java Version

Java 8

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

I tried to use turtle from CC:Tweaked to suck item from a storage (exemple: vanilla chest, drawer, dispenser...). Each time the turtle is placed next to the storage the game crash.
Tempary fix the problem by setting removeErroringEntities and removeErroringTileEntities to true in world/serverconfig/forge-server.toml and removing the annoying turtle.

### Additional Information

crash report : https://pastebin.com/PCVMruLC

**Comment by Kimapr** [comment] 2022-01-09 14:33
Can confirm; The fix is to update Supplementaries (and CC:T too, just in case). The bug is caused by Supplementaries bundling CC:T's classes with the mod, CC:T later changing the classes, making Supplementaries' bundled copy incompatible. More info [here](https://github.com/cc-tweaked/CC-Tweaked/issues/972) and [here](https://github.com/MehVahdJukaar/Supplementaries/issues/144)

**Comment by sam-kirby** [comment] 2022-04-27 09:07
Fixed in 1.0.5

**Closed by sam-kirby** 2022-04-27 09:07 UTC
Labels: bug
