### ISSUE TITLE
[Bug]: Crash when clicking on mining turtle

### ISSUE THREAD

**Issue by triplrrr** [DarkPacks/SkyFactory-One#162] opened 2022-01-19 20:24 UTC
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.4

### Java version

Java 8 update 311

### Modpack Launcher Used

MultiMC

### Memory Allocated

8 GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [X] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Game crashes when I click on a mining turtle. also seems to corrupt the world. In a previous world, i was able to click on the turtle a few times before a crash occurred, but in this world, the crash occurred the first time i clicked the turtle. i had reinstalled the modpack after the first crash because it seemed to corrupt a file, making the instance crash every time it was started. 

### Additional Information

[log and crash report](https://gist.github.com/triplrrr/67d1a52fe780d731a839d2d9e3efd84d)

**Comment by triplrrr** [comment] 2022-01-20 23:21
as far as im concerned, the pack is unplayable until this is resolved. having not only my instance but also my worlds corrupted like this is extremely frustrating

**Comment by sam-kirby** [comment] 2022-01-21 10:17
Duplicate of #157 

Darkosto has been ill recently and so there have been no updates; please be patient.

The fix is trivial and documented in the linked issue.

**Closed by sam-kirby** 2022-01-21 10:17 UTC
Labels: bug
