### ISSUE TITLE
[Bug]: material stonework factory not crushing netherrack

### ISSUE THREAD

**Issue by spacemex** [DarkPacks/SkyFactory-One#136] opened 2021-11-09 18:30 UTC
### General Info

- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.2

### Java version

openjdk jdk-11.0.12.7

### Modpack Launcher Used

multimc

### Memory Allocated

10GB

### Minecraft World Environment

Single Player

### Misc Client Info

- [X] Optifine Installed
- [X] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

In the material stonework factory you cannot crush nether rack.

**Comment by Darkosto** [comment] 2021-11-11 22:16
Duplicate of https://github.com/DarkPacks/SkyFactory-One/issues/125

**Closed by Darkosto** 2021-11-11 22:16 UTC
Labels: bug
