### ISSUE TITLE
[Bug]: Unable to access Jarfile Forge

### ISSUE THREAD

**Issue by MrMeerkat37** [DarkPacks/SkyFactory-One#156] opened 2021-12-21 14:46 UTC
### General Info

- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.4

### Java version

Java 8

### Modpack Launcher Used

Curseforge

### Memory Allocated

4gb

### Minecraft World Environment

Server

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

When launching the serverstart.bat i get: Unable to access jarfile forge-1.16.5-36.2.19.jar

Am I missing something obvious because im reading the README file and this shouldnt happen.

**Comment by sam-kirby** [comment] 2021-12-21 16:08
Have you:
1) extracted the server files from the zip archive into a folder your user has read/write access to?
2) run the install script before trying to launch the server?

If the answer to both is yes, then please can you share the installation log? It should be in the same folder as the install script.

**Comment by artdude543** [comment] 2021-12-21 18:39
A duplicate of #153 fix is being made. But was halted due to issues with CF upload API. Progress should be made today or tomorrow.

**Closed by artdude543** 2021-12-21 18:39 UTC
Labels: bug, Need More Information
