### ISSUE TITLE
[Bug]: NO recipe for Jade Wool

### ISSUE THREAD

**Issue by 533saw5** [DarkPacks/SkyFactory-One#129] opened 2021-11-05 17:03 UTC
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.2

### Java version

Java 8 Update 291

### Modpack Launcher Used

Curseforge

### Memory Allocated

6gb

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

Unable to craft Jade Wool, neither by selecting in JEI or by manually adding white wool and dye to crafting grid

**Comment by sam-kirby** [comment] 2021-11-05 17:11
Duplicate of #122

Fixed for next release.

**Closed by sam-kirby** 2021-11-05 17:11 UTC
Labels: bug
