### ISSUE TITLE
[Bug]: Easy Netherite

### ISSUE THREAD

**Issue by sindacrof** [DarkPacks/SkyFactory-One#81] opened 2021-10-21 21:02 UTC
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Netherrite is easily duped (might be considered a bug). By creating ancient debris (1x netherite and 1x obsidian) then putting that debris into an induction smelter, you get two netherite. Rinse and repeat with barely any effort.

**Comment by Darkosto** [comment] 2021-10-21 21:59
When filling out the bug reports, can you please add the information we ask for specifically the pack version you're on. Often, people report bugs on old versions of the pack that have been fixed.

Also, this is a duplicate of: https://github.com/DarkPacks/SkyFactory-One/issues/64

**Closed by Darkosto** 2021-10-21 21:59 UTC
Labels: enhancement
